
/* Generated By:JJTree: Do not edit this line. javacc.ASTArrayInit.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayInit extends SimpleNode {

  public ASTArrayInit(int id) {
    super(id);
  }

  public ASTArrayInit(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String toString(){
    return "Array " + this.identity + " = ";
  }
}
/* JavaCC - OriginalChecksum=ae6d23a8fc26b05b61ab851153c86c0c (do not edit this line) */
