/* Generated By:JJTree: Do not edit this line. javacc.ASTArrayAccess.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAccess extends SimpleNode {
  public ASTArrayAccess(int id) {
    super(id);
    this.identity = "ArrayAccess";
    this.return_type = "int";
  }

  public ASTArrayAccess(Javamm p, int id) {
    super(p, id);
    this.identity = "ArrayAccess";
    this.return_type = "nint";
  }

  @Override
  public void checkNodeSemantics(SymbolTable symbol_table) {
    if(this.jjtGetNumChildren() == 2) {
      SimpleNode left_child = (SimpleNode) this.jjtGetChild(0);

      if (!symbol_table.checkVariableType(this.getScope(), left_child.getIdentity(), "int[]"))
        SemanticErrorHandler.getInstance().printError(this.getScope(),
                "Can not access an element of a variable that is not an array: " + left_child.getIdentity());
    }
  }
}
/* JavaCC - OriginalChecksum=bc699f3d3143c9e0cad3b348c4d37626 (do not edit this line) */
