/* Generated By:JJTree: Do not edit this line. javacc.ASTArrayAccess.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArrayAccess extends SimpleNode {
  public ASTArrayAccess(int id) {
    super(id);
    this.identity = "ArrayAccess";
  }

  public ASTArrayAccess(Javamm p, int id) {
    super(p, id);
    this.identity = "ArrayAccess";
  }

}
/* JavaCC - OriginalChecksum=bc699f3d3143c9e0cad3b348c4d37626 (do not edit this line) */
