
/* Generated By:JJTree: Do not edit this line. javacc.ASTAnd.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAnd extends SimpleNode {
  public ASTAnd(int id) {
    super(id);
    this.return_type = "boolean";
  }

  public ASTAnd(Javamm p, int id) {
    super(p, id);
    this.return_type = "boolean";
  }

  @Override
  public String toString(){
    return "&&";
  }



}
/* JavaCC - OriginalChecksum=237089df49022529c77790c4eb238346 (do not edit this line) */
