
/* Generated By:JJTree: Do not edit this line. javacc.ASTArguments.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArguments extends SimpleNode {
  public ASTArguments(int id) {
    super(id);
  }

  public ASTArguments(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=bb1a507e635be036f55ea1404cb77b9b (do not edit this line) */
