/* Generated By:JJTree: Do not edit this line. ASTAssignement.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTAssignement extends SimpleNode {
  public ASTAssignement(int id) {
    super(id);
  }

  public ASTAssignement(Javamm p, int id) {
    super(p, id);
  }

  @Override
  protected void checkNodeSemantics(SymbolTable symbol_table) {
    SimpleNode left_child = (SimpleNode) this.jjtGetChild(0); //var init - nome da variavel no identity
    SimpleNode right_child = (SimpleNode) this.jjtGetChild(1); //expressão ou whatever

    if(!left_child.getReturnType(symbol_table).equals(right_child.getReturnType(symbol_table))){
      SemanticErrorHandler.getInstance().printError(this.getScope(),
              this + " assign operation with different types ",
              left_child.identity + " = " + right_child.identity);
    }
    else if(!symbol_table.checkInitializationVariable(left_child.identity , this.getScope()))
    {
      System.out.println("INITIALIZING.....................");
      symbol_table.initializeVariable(left_child.identity, this.getScope());
    };

  }

}
/* JavaCC - OriginalChecksum=236b2102da430414dc6ba7c699d0cbfb (do not edit this line) */
