

/* Generated By:JJTree: Do not edit this line. javacc.ASTArgument.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTArgument extends SimpleNode {
  public ASTArgument(int id) {
    super(id);
  }

  public ASTArgument(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String toString(){
    return this.type + " " + this.identity;
  }
}
/* JavaCC - OriginalChecksum=95a59bce5d1db2950b7d5dcc42146311 (do not edit this line) */
