
/* Generated By:JJTree: Do not edit this line. javacc.ASTAdditionSubtraction.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTAdditionSubtraction extends SimpleNode {
  protected String operator;

  public ASTAdditionSubtraction(int id) {
    super(id);
    this.return_type = "int";
  }

  public ASTAdditionSubtraction(Javamm p, int id) {
    super(p, id);
    this.return_type = "int";
  }

  public String getOperator(){
    return this.operator;
  }

  public void setOperator(String operator){
    this.operator = operator;
  }

  @Override
  public String toString(){
    return this.operator;
  }

}
/* JavaCC - OriginalChecksum=b661bd7b050d3e1baf919c7573f0190a (do not edit this line) */
