import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. ASTDot.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTDot extends SimpleNode {
  private  boolean already_calculated_return;
  public ASTDot(int id) {
    super(id);
    this.identity = ".";
    this.return_type="";
    already_calculated_return = false;
  }

  public ASTDot(Javamm p, int id) {
    super(p, id);
    this.identity = ".";
    this.return_type="";
    already_calculated_return = false;
  }

  @Override
  public String getReturnType(SymbolTable symbol_table){
    if(this.return_type=="" && !already_calculated_return)
      setReturnType(symbol_table);
    return this.return_type;
  }

  @Override
  public String getReturnType(){
    return this.return_type;
  }

  private void setReturnType(SymbolTable symbol_table){
    if(this.jjtGetNumChildren() == 2) {
      SimpleNode left_child = (SimpleNode) this.jjtGetChild(0);
      SimpleNode right_child = (SimpleNode) this.jjtGetChild(1);

      if(right_child.getIdentity() == "length"){
        if(symbol_table.checkVariableType(this.getScope(), left_child.getIdentity(), "int[]") ||
                symbol_table.checkMethodType(left_child.getIdentity(), "int[]")){
          this.return_type="int";
        }
      }
      else if((left_child.getIdentity()=="new" && symbol_table.isClass(left_child.getReturnType())) ||
              left_child.getIdentity()=="this" || symbol_table.isClass(left_child.getIdentity()) ||
              symbol_table.checkVariableType(this.getScope(), left_child.getIdentity(), symbol_table.class_name)){

        ArrayList<String> arguments = right_child.getParameters(symbol_table);

        //result<error,return_type>
        Pair<String, String> result = symbol_table.getMethodReturnType(right_child.getIdentity(), arguments);

        return_type = result.second;

        if(return_type == "") {
          checkError(result.first, left_child.toString() + "." + right_child.toString());
        }
      }
      else {
        ArrayList<String> arguments = right_child.getParameters(symbol_table);
        Pair<String, String> result = symbol_table.getImportReturnType(left_child.getIdentity(), right_child.getIdentity(), arguments);

        return_type = result.second;
        if(return_type == "") {
          checkError(result.first, left_child.toString() + "." + right_child.toString());
        }
      }
    }
    this.already_calculated_return = true;
  }

  private void checkError(String error, String code) {
    if (error != null)
      SemanticErrorHandler.getInstance().printError(this.getScope(),
              error, code);
  }

  @Override
  public void checkNodeSemantics(SymbolTable symbol_table){
    if(getReturnType(symbol_table) == "") {
      SimpleNode left_child = (SimpleNode) this.jjtGetChild(0);
      SimpleNode right_child = (SimpleNode) this.jjtGetChild(1);

      SemanticErrorHandler.getInstance().printError(this.getScope(),
              "Dot expression in not correctly defined or does not exist.",
              left_child.toString() + "." + right_child.toString());
    }
  }

  @Override
  public String toString(){
    return ".";
  }

}
/* JavaCC - OriginalChecksum=b8e6e003bad221985a0315e9e5ebd369 (do not edit this line) */
