
/* Generated By:JJTree: Do not edit this line. javacc.ASTExpressionNew.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionNew extends SimpleNode {
  public ASTExpressionNew(int id) {
    super(id);
  }

  public ASTExpressionNew(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String toString(){
    return "new " + this.getReturnType();
  }

}
/* JavaCC - OriginalChecksum=a9713694f6cac9b23d6882fd83238429 (do not edit this line) */
