

/* Generated By:JJTree: Do not edit this line. javacc.ASTExpression.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpression extends SimpleNode {
  public ASTExpression(int id) {
    super(id);
  }

  public ASTExpression(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3d310972355bcfa083b6e8f0145657af (do not edit this line) */
