

/* Generated By:JJTree: Do not edit this line. javacc.ASTExpressionIntermediateDivision.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionIntermediateDivision extends SimpleNode {
  public ASTExpressionIntermediateDivision(int id) {
    super(id);
  }

  public ASTExpressionIntermediateDivision(Javamm p, int id) {
    super(p, id);
  }


}
/* JavaCC - OriginalChecksum=89822b523ca749c0f3dc49e8d793626d (do not edit this line) */
