import java.util.ArrayList;

/* Generated By:JJTree: Do not edit this line. javacc.ASTExpressionDot.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExpressionDot extends SimpleNode {
  public ASTExpressionDot(int id) {
    super(id);
  }

  public ASTExpressionDot(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public ArrayList<String> getParameters(SymbolTable symbol_table){
    return ((SimpleNode) this.jjtGetChild(0)).getParameters(symbol_table);
  }

  @Override
  public String toString(){
    return this.identity;
  }
}
/* JavaCC - OriginalChecksum=2e40fd5ec8de7211dc2f7f34a8344149 (do not edit this line) */
