

/* Generated By:JJTree: Do not edit this line. javacc.ASTExtends.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTExtends extends SimpleNode {
  public ASTExtends(int id) {
    super(id);
  }

  public ASTExtends(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c3586cd7393f2a4b73d0891ee09b32fa (do not edit this line) */
