
/* Generated By:JJTree: Do not edit this line. javacc.ASTFalse.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFalse extends SimpleNode {
  public ASTFalse(int id) {
    super(id);
  }

  public ASTFalse(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=ddb2f9f36a8d2a3b2a0c210a63188da3 (do not edit this line) */
