
/* Generated By:JJTree: Do not edit this line. javacc.ASTIf.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIf extends SimpleNode {
  public ASTIf(int id) {
    super(id);
  }

  public ASTIf(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=04ee7893447596dd3d1759e2d7db89ef (do not edit this line) */
