
/* Generated By:JJTree: Do not edit this line. javacc.ASTIndex.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIndex extends SimpleNode {
  public ASTIndex(int id) {
    super(id);
    this.return_type="int";
  }

  public ASTIndex(Javamm p, int id) {
    super(p, id);
    this.return_type="int";
  }

  @Override
  public String toString(){
    return "Index";
  }

}
/* JavaCC - OriginalChecksum=b7796a22346b260640cf30c42b33fc6d (do not edit this line) */
