

/* Generated By:JJTree: Do not edit this line. javacc.ASTID.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTID extends SimpleNode {
  public ASTID(int id) {
    super(id);
  }

  public ASTID(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=28a0e7985073fe41c798463bd70b5ce9 (do not edit this line) */
