/* Generated By:JJTree: Do not edit this line. ASTImport.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImport extends SimpleNode {
  private boolean isStatic = false;
  private String className;
  private String methodName;
  public String returnType;

  public ASTImport(int id) {
    super(id);
  }

  public ASTImport(Javamm p, int id) {
    super(p, id);
  }

  public void setStatic(boolean aStatic) {
    this.isStatic = aStatic;
  }

  public void setClassName(String className) {
    this.className = className;
  }

  public void setMethodName(String methodName) {
    this.methodName = methodName;
  }

  public void setReturnType(String returnType) {
    this.returnType = returnType;
  }

  public String toString() {
    String pstatic = "";
    if(isStatic)
      pstatic = "static ";

    if(methodName == null)
      methodName = "";
    else
      methodName += " ";

    if(returnType == null)
        returnType = "void";

    return "Import " + pstatic + className + " " + methodName + returnType;
  }
}
/* JavaCC - OriginalChecksum=cb28638552a82c93cdcbeca9d244874a (do not edit this line) */
