/* Generated By:JJTree: Do not edit this line. ASTIfBody.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfBody extends SimpleNode {
  public ASTIfBody(int id) {
    super(id);
  }

  public ASTIfBody(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=972e30f6c105abfc6352b44c58736218 (do not edit this line) */
