/* Generated By:JJTree: Do not edit this line. ASTIfElse.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTIfElse extends SimpleNode {
  public ASTIfElse(int id) {
    super(id);
  }

  public ASTIfElse(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5b52fc61f60d51ad39d84bbb32a13083 (do not edit this line) */
