
/* Generated By:JJTree: Do not edit this line. javacc.ASTInteger.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTInteger extends SimpleNode {
  public ASTInteger(int id) {
    super(id);
    return_type = "int";
  }

  public ASTInteger(Javamm p, int id) {
    super(p, id);
    return_type = "int";
  }

  @Override
  public String toString(){
    return this.identity;
  }

}
/* JavaCC - OriginalChecksum=b270f48c5b9de9cbf70f76636e591e23 (do not edit this line) */
