
/* Generated By:JJTree: Do not edit this line. javacc.ASTImport.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImport extends SimpleNode {
  public ASTImport(int id) {
    super(id);
  }

  public ASTImport(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=cb28638552a82c93cdcbeca9d244874a (do not edit this line) */
