
/* Generated By:JJTree: Do not edit this line. javacc.ASTImportDeclarationDot.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTImportDeclarationDot extends SimpleNode {
  public ASTImportDeclarationDot(int id) {
    super(id);
  }

  public ASTImportDeclarationDot(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a9241f70661f20c5007856ee4d3cf0c0 (do not edit this line) */
