import javacc.SemanticErrorHandler;

/* Generated By:JJTree: Do not edit this line. javacc.ASTLessThan.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessThan extends SimpleNode {
  protected final String operator = "<";

  public ASTLessThan(int id) {
    super(id);
    this.binary_operator=true;
  }

  public ASTLessThan(Javamm p, int id) {
    super(p, id);
    this.binary_operator=true;
  }

  @Override
  public String toString(){
    return "<";
  }

  @Override
  protected void checkNodeSemantics(SymbolTable symbol_table) {
    if(this.jjtGetNumChildren() == 2) {
      SimpleNode left_child = (SimpleNode) this.jjtGetChild(0);
      SimpleNode right_child = (SimpleNode) this.jjtGetChild(1);

      System.out.println("AARGH AARGH DIBADIDI: " + left_child.toString() + operator + right_child.toString());



      if(!left_child.isBinaryOperator()){
        if(!(left_child.getType() == "int" || symbol_table.checkVariable(this.getScope(), left_child.getIdentity(), "int"))){
          SemanticErrorHandler.getInstance().printError(this.getScope(),
                  "Left child of operator " + operator + " has to be an integer or a integer variable",
                  left_child.toString() + operator + right_child.toString());
        }
      }
      if(!right_child.isBinaryOperator()){
        if(!(right_child.getType() == "int" || symbol_table.checkVariable(this.getScope(), right_child.getIdentity(), "int"))){
          SemanticErrorHandler.getInstance().printError(this.getScope(),
                  "Right child of operator " + operator + " has to be an integer or a integer variable",
                  left_child.toString() + operator + right_child.toString());
        }
      }
    }
  }

}
/* JavaCC - OriginalChecksum=a49d16480236596266a2592809b263e3 (do not edit this line) */
