
/* Generated By:JJTree: Do not edit this line. javacc.ASTLessThan.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public class ASTLessThan extends SimpleNode {
  private static int counter = 0;
  private int count;
  protected final String operator = "<";

  public ASTLessThan(int id) {
    super(id);
    this.binary_operator=true;
    this.return_type="boolean";
    this.count = counter;
    counter++;
  }

  public ASTLessThan(Javamm p, int id) {
    super(p, id);
    this.binary_operator=true;
    this.return_type="boolean";
    this.count = counter;
    counter++;
  }

  @Override
  public int getCount() {
    return this.count;
  }

  @Override
  public String toString(){
    return "<";
  }

  @Override
  protected void checkNodeSemantics(SymbolTable symbol_table) {
    ArithmeticSemantic.checkNodeSemantics(symbol_table, this, operator);
  }
}
/* JavaCC - OriginalChecksum=a49d16480236596266a2592809b263e3 (do not edit this line) */
