
/* Generated By:JJTree: Do not edit this line. javacc.ASTMain.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMain extends SimpleNode {
  public ASTMain(int id) {
    super(id);
  }

  public ASTMain(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8b697e6a65243899f7f329d4eb7aa092 (do not edit this line) */
