
/* Generated By:JJTree: Do not edit this line. javacc.ASTMultiplicationDivision.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTMultiplicationDivision extends SimpleNode {
  protected String operator;

  public ASTMultiplicationDivision(int id) {
    super(id);
    this.return_type = "int";
    this.binary_operator=true;
  }

  public ASTMultiplicationDivision(Javamm p, int id) {
    super(p, id);
    this.return_type = "int";
    this.binary_operator=true;
  }

  public String getOperator(){
    return this.operator;
  }

  public void setOperator(String operator){
    this.operator = operator;
  }

  @Override
  public String toString(){
    return this.operator;
  }

  @Override
  protected void checkNodeSemantics(SymbolTable symbol_table) {
    ArithmeticSemantic.checkNodeSemantics(symbol_table, this, operator);
  }
}
/* JavaCC - OriginalChecksum=fe073846e3de52a6d7fa39761df70aab (do not edit this line) */
