

/* Generated By:JJTree: Do not edit this line. javacc.ASTNot.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTNot extends SimpleNode {
  public ASTNot(int id) {
    super(id);
    this.return_type="boolean";
  }

  public ASTNot(Javamm p, int id) {
    super(p, id);
    this.return_type="boolean";
  }

  @Override
  public String toString(){
    return "!";
  }
}
/* JavaCC - OriginalChecksum=b66090c93e68e0e5e6bff2561dcc7c8c (do not edit this line) */
