
/* Generated By:JJTree: Do not edit this line. javacc.ASTStart.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTStart extends SimpleNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=12b14e2310f9eca22f42c118d0e048c0 (do not edit this line) */
