

/* Generated By:JJTree: Do not edit this line. javacc.ASTTerminal.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTerminal extends SimpleNode {
  public ASTTerminal(int id) {
    super(id);
  }

  public ASTTerminal(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1d06e02144c6e64910974250d25e21cd (do not edit this line) */
