/* Generated By:JJTree: Do not edit this line. javacc.ASTThis.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTThis extends SimpleNode {
  public ASTThis(int id) {
    super(id);
    this.identity="this";
  }

  public ASTThis(Javamm p, int id) {
    super(p, id);
    this.identity="this";
  }

}
/* JavaCC - OriginalChecksum=4cc6659f8df61343e257563ecc490fd8 (do not edit this line) */
