

/* Generated By:JJTree: Do not edit this line. javacc.ASTType.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTType extends SimpleNode {
  public ASTType(int id) {
    super(id);
  }

  public ASTType(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=622d43c47c6789196b198d0f69b2011b (do not edit this line) */
