

/* Generated By:JJTree: Do not edit this line. javacc.ASTTrue.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTTrue extends SimpleNode {
  public ASTTrue(int id) {
    super(id);
  }

  public ASTTrue(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f4ed6235d306ce6e2f8fe20c704fef65 (do not edit this line) */
