

/* Generated By:JJTree: Do not edit this line. javacc.ASTVariableInit.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVariableInit extends SimpleNode {
  public ASTVariableInit(int id) {
    super(id);
  }

  public ASTVariableInit(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=214a877005ca30c0c4f59a6543dd794e (do not edit this line) */
