
/* Generated By:JJTree: Do not edit this line. javacc.ASTVar.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVar extends SimpleNode {
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=551f7e36da7ebe122aa0e4faca398a30 (do not edit this line) */
