

/* Generated By:JJTree: Do not edit this line. javacc.ASTVarInit.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarInit extends SimpleNode {
  public ASTVarInit(int id) {
    super(id);
  }

  public ASTVarInit(Javamm p, int id) {
    super(p, id);
  }

  @Override
  public String toString(){
    return this.identity + " = ";
  }

}
/* JavaCC - OriginalChecksum=fbaeb98e7c33909d7cc13b721b1a7b21 (do not edit this line) */
