/* Generated By:JJTree: Do not edit this line. ASTVarDeclaration.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTVarDeclaration extends SimpleNode {
  public ASTVarDeclaration(int id) {
    super(id);
  }

  public ASTVarDeclaration(Javamm p, int id) {
    super(p, id);
  }

  public String toString() {
    return this.type + " " + this.identity;
  }
}
/* JavaCC - OriginalChecksum=8f72e5c259da2033e8a451a9ce073fa3 (do not edit this line) */
