
/* Generated By:JJTree: Do not edit this line. javacc.ASTWhile.java Version 6.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTWhile extends SimpleNode {
  public ASTWhile(int id) {
    super(id);
  }

  public ASTWhile(Javamm p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=2706f5e4eb3caeff77af14b38670635b (do not edit this line) */
