/* Generated By:JavaCC: Do not edit this line. JavammTreeConstants.java Version 6.1_2 */
public interface JavammTreeConstants
{
  public int JJTSTART = 0;
  public int JJTIMPORT = 1;
  public int JJTVOID = 2;
  public int JJTCLASS = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMAIN = 5;
  public int JJTMETHOD = 6;
  public int JJTARGUMENT = 7;
  public int JJTIF = 8;
  public int JJTWHILE = 9;
  public int JJTASSIGNEMENT = 10;
  public int JJTVARINIT = 11;
  public int JJTINDEX = 12;
  public int JJTARRAYINIT = 13;
  public int JJTAND = 14;
  public int JJTLESSTHAN = 15;
  public int JJTADDITIONSUBTRACTION = 16;
  public int JJTMULTIPLICATIONDIVISION = 17;
  public int JJTNOT = 18;
  public int JJTDOT = 19;
  public int JJTINTEGER = 20;
  public int JJTTRUE = 21;
  public int JJTFALSE = 22;
  public int JJTTHIS = 23;
  public int JJTID = 24;
  public int JJTARRAYACCESS = 25;
  public int JJTEXPRESSIONDOT = 26;
  public int JJTEXPRESSIONNEW = 27;


  public String[] jjtNodeName = {
    "Start",
    "Import",
    "void",
    "Class",
    "VarDeclaration",
    "Main",
    "Method",
    "Argument",
    "If",
    "While",
    "Assignement",
    "VarInit",
    "Index",
    "ArrayInit",
    "And",
    "LessThan",
    "AdditionSubtraction",
    "MultiplicationDivision",
    "Not",
    "Dot",
    "Integer",
    "True",
    "False",
    "This",
    "ID",
    "ArrayAccess",
    "ExpressionDot",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=fef5f216833846cd84dfec0202ae6d6f (do not edit this line) */
