/* Generated By:JavaCC: Do not edit this line. JavammTreeConstants.java Version 6.1_2 */
public interface JavammTreeConstants
{
  public int JJTSTART = 0;
  public int JJTIMPORT = 1;
  public int JJTVOID = 2;
  public int JJTCLASS = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTMAIN = 5;
  public int JJTMETHOD = 6;
  public int JJTRETURN = 7;
  public int JJTARGUMENT = 8;
  public int JJTIF = 9;
  public int JJTIFBODY = 10;
  public int JJTIFELSE = 11;
  public int JJTWHILE = 12;
  public int JJTASSIGNEMENT = 13;
  public int JJTVARINIT = 14;
  public int JJTARRAYINIT = 15;
  public int JJTINDEX = 16;
  public int JJTAND = 17;
  public int JJTLESSTHAN = 18;
  public int JJTADDITIONSUBTRACTION = 19;
  public int JJTMULTIPLICATIONDIVISION = 20;
  public int JJTNOT = 21;
  public int JJTDOT = 22;
  public int JJTINTEGER = 23;
  public int JJTTRUE = 24;
  public int JJTFALSE = 25;
  public int JJTTHIS = 26;
  public int JJTID = 27;
  public int JJTARRAYACCESS = 28;
  public int JJTEXPRESSIONDOT = 29;
  public int JJTFUNCTIONCALLARGUMENTS = 30;
  public int JJTEXPRESSIONNEW = 31;


  public String[] jjtNodeName = {
    "Start",
    "Import",
    "void",
    "Class",
    "VarDeclaration",
    "Main",
    "Method",
    "Return",
    "Argument",
    "If",
    "IfBody",
    "IfElse",
    "While",
    "Assignement",
    "VarInit",
    "ArrayInit",
    "Index",
    "And",
    "LessThan",
    "AdditionSubtraction",
    "MultiplicationDivision",
    "Not",
    "Dot",
    "Integer",
    "True",
    "False",
    "This",
    "ID",
    "ArrayAccess",
    "ExpressionDot",
    "FunctionCallArguments",
    "ExpressionNew",
  };
}
/* JavaCC - OriginalChecksum=101f57f79d5935885e2f376c18c207d1 (do not edit this line) */
