/* Generated By:JJTree&JavaCC: Do not edit this line. JavammConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface JavammConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IMPORT = 7;
  /** RegularExpression Id. */
  int CLASS = 8;
  /** RegularExpression Id. */
  int EXTENDS = 9;
  /** RegularExpression Id. */
  int PUBLIC = 10;
  /** RegularExpression Id. */
  int STATIC = 11;
  /** RegularExpression Id. */
  int VOID = 12;
  /** RegularExpression Id. */
  int NEW = 13;
  /** RegularExpression Id. */
  int LEN = 14;
  /** RegularExpression Id. */
  int MAIN = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int INT = 17;
  /** RegularExpression Id. */
  int BOOLEAN = 18;
  /** RegularExpression Id. */
  int IF = 19;
  /** RegularExpression Id. */
  int THEN = 20;
  /** RegularExpression Id. */
  int ELSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int TRUE = 23;
  /** RegularExpression Id. */
  int FALSE = 24;
  /** RegularExpression Id. */
  int THIS = 25;
  /** RegularExpression Id. */
  int LTHAN = 26;
  /** RegularExpression Id. */
  int GTHAN = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int ASTERISK = 30;
  /** RegularExpression Id. */
  int FSLASH = 31;
  /** RegularExpression Id. */
  int EQUALS = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int SEMICOL = 34;
  /** RegularExpression Id. */
  int COL = 35;
  /** RegularExpression Id. */
  int DOT = 36;
  /** RegularExpression Id. */
  int NOT = 37;
  /** RegularExpression Id. */
  int OCURLY = 38;
  /** RegularExpression Id. */
  int CCURLY = 39;
  /** RegularExpression Id. */
  int OPAREN = 40;
  /** RegularExpression Id. */
  int CPAREN = 41;
  /** RegularExpression Id. */
  int OSBRACKET = 42;
  /** RegularExpression Id. */
  int CSBRACKET = 43;
  /** RegularExpression Id. */
  int RETURN = 44;
  /** RegularExpression Id. */
  int NUM = 45;
  /** RegularExpression Id. */
  int ID = 46;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "\"import\"",
    "\"class\"",
    "\"extends\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"new\"",
    "\"length\"",
    "\"main\"",
    "\"String\"",
    "\"int\"",
    "\"boolean\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"true\"",
    "\"false\"",
    "\"this\"",
    "\"<\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"&&\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"return\"",
    "<NUM>",
    "<ID>",
  };

}
