/* Generated By:JavaCC: Do not edit this line. JavammTreeConstants.java Version 5.0 */
public interface JavammTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTTERM = 2;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Term",
  };
}
/* JavaCC - OriginalChecksum=e5b60f17ca61549e90d5919c6b1c4bc5 (do not edit this line) */
